[platformio]
default_envs = esp32c3_supermini

[env:esp32c3_supermini]
platform = espressif32@6.12.0
board = esp32-c3-devkitm-1
framework = arduino
build_src_filter =
  +<main.cpp>
  +<camera/BlackmagicCamera.cpp>
  +<config/Settings.cpp>
  +<msp/MspClient.cpp>
  +<web/WebUi.cpp>
monitor_speed = 115200
upload_speed = 921600
board_build.flash_mode = dio
board_build.flash_size = 4MB
build_flags =
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D ARDUINO_USB_MODE=1
  -D CORE_DEBUG_LEVEL=1
lib_deps =
  h2zero/NimBLE-Arduino@2.3.7
